// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/proto.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Sku struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cover                string   `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`
	GoodsId              int64    `protobuf:"varint,4,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	Price                int64    `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Inventory            int64    `protobuf:"varint,6,opt,name=inventory,proto3" json:"inventory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sku) Reset()         { *m = Sku{} }
func (m *Sku) String() string { return proto.CompactTextString(m) }
func (*Sku) ProtoMessage()    {}
func (*Sku) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{0}
}

func (m *Sku) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sku.Unmarshal(m, b)
}
func (m *Sku) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sku.Marshal(b, m, deterministic)
}
func (m *Sku) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sku.Merge(m, src)
}
func (m *Sku) XXX_Size() int {
	return xxx_messageInfo_Sku.Size(m)
}
func (m *Sku) XXX_DiscardUnknown() {
	xxx_messageInfo_Sku.DiscardUnknown(m)
}

var xxx_messageInfo_Sku proto.InternalMessageInfo

func (m *Sku) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Sku) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Sku) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *Sku) GetGoodsId() int64 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *Sku) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Sku) GetInventory() int64 {
	if m != nil {
		return m.Inventory
	}
	return 0
}

type GetGoodsDetailReq struct {
	GoodsId              int64    `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGoodsDetailReq) Reset()         { *m = GetGoodsDetailReq{} }
func (m *GetGoodsDetailReq) String() string { return proto.CompactTextString(m) }
func (*GetGoodsDetailReq) ProtoMessage()    {}
func (*GetGoodsDetailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{1}
}

func (m *GetGoodsDetailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGoodsDetailReq.Unmarshal(m, b)
}
func (m *GetGoodsDetailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGoodsDetailReq.Marshal(b, m, deterministic)
}
func (m *GetGoodsDetailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGoodsDetailReq.Merge(m, src)
}
func (m *GetGoodsDetailReq) XXX_Size() int {
	return xxx_messageInfo_GetGoodsDetailReq.Size(m)
}
func (m *GetGoodsDetailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGoodsDetailReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetGoodsDetailReq proto.InternalMessageInfo

func (m *GetGoodsDetailReq) GetGoodsId() int64 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

type GetGoodsDetailRes struct {
	GoodsId              int64    `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Images               string   `protobuf:"bytes,3,opt,name=images,proto3" json:"images,omitempty"`
	Status               int32    `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Skus                 []*Sku   `protobuf:"bytes,5,rep,name=skus,proto3" json:"skus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGoodsDetailRes) Reset()         { *m = GetGoodsDetailRes{} }
func (m *GetGoodsDetailRes) String() string { return proto.CompactTextString(m) }
func (*GetGoodsDetailRes) ProtoMessage()    {}
func (*GetGoodsDetailRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{2}
}

func (m *GetGoodsDetailRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGoodsDetailRes.Unmarshal(m, b)
}
func (m *GetGoodsDetailRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGoodsDetailRes.Marshal(b, m, deterministic)
}
func (m *GetGoodsDetailRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGoodsDetailRes.Merge(m, src)
}
func (m *GetGoodsDetailRes) XXX_Size() int {
	return xxx_messageInfo_GetGoodsDetailRes.Size(m)
}
func (m *GetGoodsDetailRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGoodsDetailRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetGoodsDetailRes proto.InternalMessageInfo

func (m *GetGoodsDetailRes) GetGoodsId() int64 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *GetGoodsDetailRes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetGoodsDetailRes) GetImages() string {
	if m != nil {
		return m.Images
	}
	return ""
}

func (m *GetGoodsDetailRes) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetGoodsDetailRes) GetSkus() []*Sku {
	if m != nil {
		return m.Skus
	}
	return nil
}

func init() {
	proto.RegisterType((*Sku)(nil), "sku")
	proto.RegisterType((*GetGoodsDetailReq)(nil), "get_goods_detail_req")
	proto.RegisterType((*GetGoodsDetailRes)(nil), "get_goods_detail_res")
}

func init() { proto.RegisterFile("api/proto/proto.proto", fileDescriptor_ef32c37ea206d67b) }

var fileDescriptor_ef32c37ea206d67b = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x85, 0x4d, 0xff, 0xc6, 0xb9, 0x82, 0x48, 0x98, 0x91, 0x28, 0x2e, 0x4a, 0x57, 0x5d, 0x55,
	0x1c, 0xdf, 0x60, 0x76, 0xba, 0xec, 0xd2, 0x4d, 0x89, 0x93, 0x50, 0x42, 0x7f, 0x52, 0x73, 0xd3,
	0x01, 0x5f, 0x42, 0x5f, 0x59, 0xe6, 0xb6, 0x20, 0x23, 0xc5, 0xcd, 0x4d, 0xce, 0x17, 0x4e, 0x4e,
	0x0e, 0x81, 0xad, 0x1c, 0xcc, 0xe3, 0xe0, 0xac, 0xb7, 0xd3, 0x2c, 0x68, 0x66, 0x5f, 0x0c, 0x42,
	0x6c, 0x46, 0x7e, 0x0d, 0x81, 0x51, 0x82, 0xa5, 0x2c, 0x0f, 0xcb, 0xc0, 0x28, 0xce, 0x21, 0xea,
	0x65, 0xa7, 0x45, 0x90, 0xb2, 0x7c, 0x5d, 0xd2, 0x9e, 0x6f, 0x20, 0x3e, 0xd8, 0xa3, 0x76, 0x22,
	0x24, 0x38, 0x09, 0x7e, 0x07, 0x97, 0xb5, 0xb5, 0x0a, 0x2b, 0xa3, 0x44, 0x44, 0xfe, 0x15, 0xe9,
	0x17, 0x75, 0x32, 0x0c, 0xce, 0x1c, 0xb4, 0x88, 0x89, 0x4f, 0x82, 0x3f, 0xc0, 0xda, 0xf4, 0x47,
	0xdd, 0x7b, 0xeb, 0x3e, 0x45, 0x42, 0x27, 0xbf, 0x20, 0x7b, 0x82, 0x4d, 0xad, 0x7d, 0x35, 0x5d,
	0xa9, 0xb4, 0x97, 0xa6, 0xad, 0x9c, 0xfe, 0x38, 0x8b, 0x61, 0x67, 0x31, 0xd9, 0x37, 0x5b, 0xf4,
	0xe0, 0x3f, 0x9e, 0xc5, 0x7e, 0xb7, 0x90, 0x98, 0x4e, 0xd6, 0x1a, 0xe7, 0x82, 0xb3, 0x3a, 0x71,
	0xf4, 0xd2, 0x8f, 0x48, 0xfd, 0xe2, 0x72, 0x56, 0x5c, 0x40, 0x84, 0xcd, 0x88, 0x22, 0x4e, 0xc3,
	0xfc, 0x6a, 0x17, 0x15, 0xd8, 0x8c, 0x25, 0x91, 0xdd, 0x2b, 0x44, 0x9d, 0x6c, 0x5b, 0xbe, 0x87,
	0x9b, 0xbf, 0x0f, 0xe3, 0xdb, 0x62, 0xa9, 0xdf, 0xfd, 0x22, 0xc6, 0xec, 0x62, 0xbf, 0x7a, 0x8b,
	0xe9, 0xab, 0xde, 0x13, 0x5a, 0x9e, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x66, 0x4f, 0x8f, 0x37,
	0xca, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MallClient is the client API for Mall service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MallClient interface {
	GetGoodsDetail(ctx context.Context, in *GetGoodsDetailReq, opts ...grpc.CallOption) (*GetGoodsDetailRes, error)
}

type mallClient struct {
	cc *grpc.ClientConn
}

func NewMallClient(cc *grpc.ClientConn) MallClient {
	return &mallClient{cc}
}

func (c *mallClient) GetGoodsDetail(ctx context.Context, in *GetGoodsDetailReq, opts ...grpc.CallOption) (*GetGoodsDetailRes, error) {
	out := new(GetGoodsDetailRes)
	err := c.cc.Invoke(ctx, "/mall/get_goods_detail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MallServer is the server API for Mall service.
type MallServer interface {
	GetGoodsDetail(context.Context, *GetGoodsDetailReq) (*GetGoodsDetailRes, error)
}

// UnimplementedMallServer can be embedded to have forward compatible implementations.
type UnimplementedMallServer struct {
}

func (*UnimplementedMallServer) GetGoodsDetail(ctx context.Context, req *GetGoodsDetailReq) (*GetGoodsDetailRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoodsDetail not implemented")
}

func RegisterMallServer(s *grpc.Server, srv MallServer) {
	s.RegisterService(&_Mall_serviceDesc, srv)
}

func _Mall_GetGoodsDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoodsDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallServer).GetGoodsDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mall/GetGoodsDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallServer).GetGoodsDetail(ctx, req.(*GetGoodsDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mall_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mall",
	HandlerType: (*MallServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "get_goods_detail",
			Handler:    _Mall_GetGoodsDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/proto.proto",
}
